name: Test Github Action

on:
  workflow_dispatch:
    inputs:
      pr_filter:
        description: 'Filter PRs'
        required: true
        type: choice
        options:
          - 'all'
          - 'labelled'
          - 'error'

  workflow_call:
    inputs:
      pr_filter:
        description: 'Filter PRs'
        required: false
        type: string
        default: 'labelled'

      pr_label:
        description: 'PR Label'
        required: false
        type: string
        default: 'test-autoupdate'

      base_branchs:
        description: 'Base Branches'
        required: false
        type: string
        default: 'master,main'

  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug Action
        uses: ./
        with:
          github_token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN || github.token }}
          pr_filter: ${{ github.event.inputs.pr_filter || 'all' }}
          pr_label: 'test-autoupdate'
          pr_ready_state: 'all'
          exclude_pr_label: ''
          merge_conflict_action: 'fail'
          merge_method: 'merge'
          merge_commit_message: ''
          base_branches: ${{ github.event.inputs.base_branchs || 'master,main' }}
          